# Generated by Django 4.2.23 on 2025-08-09 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, unique=True)),
                ('context', models.TextField(max_length=200)),
                ('area', models.CharField(choices=[('arithmetic', 'Arithmetic'), ('algebra', 'Algebra'), ('analysis', 'Analysis'), ('calculus', 'Calculus'), ('combinatorics', 'Combinatorics'), ('geometry', 'Geomoetry'), ('probability', 'Probability'), ('topology', 'Topology')], default='arithmetic', max_length=15)),
                ('difficulty', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('master', 'Master')], default='low', max_length=10)),
                ('resolution', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
