# Generated by Django 4.2.23 on 2025-08-09 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rename_content_post_problem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='answer',
            new_name='resolution',
        ),
    ]
