# Generated by Django 4.2.23 on 2025-08-09 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_rename_answer_comment_resolution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
